### ISSUE TITLE
Rule "studyid_not_in_content" should gracefully pass when unable to read incoming file

### ISSUE THREAD

**Issue by jujaga** [bcgov/OCWA#103]
# OCWA Issue

## User Story

**As a** _researcher_,<br>
**I want** _the "studyid_not_in_content" rule to not fail on files which do obviously do not have study ids_<br>
**so that** _I can submit files such as images and other binary content_.

### ENV

- [x] `DEV`
- [x] `TEST`
- [ ] `PROD`

### TESTCASE

- Add any image file

### EXPECTED

- The studyid_not_in_content rule should pass

### ACTUAL

- The studyid_not_in_content rule fails

## Notes

The rule needs to be rewritten to gracefully fail upon failure to decode instead of hard failing.

**Comment by jujaga** [comment]
Rule was updated to `print(not bool(re.compile(b'[\\w]{1}[\\d]{9}').search(${file.content})))` which handles binary content better and satisfies this issue.

**Comment by pripley123** [comment]
tried creating a new request in the test environment and uploaded a jpg.  Saved and closed.  Viewed the request.  Still flagged for study ids

**Comment by pripley123** [comment]
I've tried a couple of more jpg - these are passing ... so I need to narrow this down a bit

**Comment by jujaga** [comment]
Certain image files have an explicit string inside the binary which will trip the `[\w]{1}[\d]{9}` regex rule as it only looks for either
1. a letter followed by exactly 9 digits or
2. exactly 10 digits
The implemented rule is behaving as expected; however until we are provided better requirements that do not match on so many potential values, some images are inevitably going to fail.

**Comment by pripley123** [comment]
Thanks for documenting the reason for images failing.  Agreed it is expected behaviour for now.  Since the regex used to search for study ids is configurable, this seems fine for MVP
