### ISSUE TITLE
Make Variable and Sub-population fields required

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#115]
## User Story

**As a** _manager of the DI Program_,<br>
**I want** _to have variable and sub-population information for each request_<br>
**so that** _there is a place to flag sensitive variables and to accommodate future governance changes_.

### ENV

- [x] `DEV`
- [x] `TEST`

Acceptance criteria:
Variable and Sub-population fields are made to be required
Field labels / helper text updated as per below

Describe the data used, to better understand the population and population attributes

VARIABLES:  Provide a description of original and self-constructed variables (include full labeling of all variables and value labels)	
SUB-POPULATION: In the case of sub-samples and sub-populations, the selection criteria and size of the sub-samples	

INSTRUCTION:  Please ensure that you also have the following elements, as appropriate, with your output submission: descriptive labeling (ideally alongside each component), information for specific output types, and, log files or annotated steps of analysis.

**Comment by Jonesy** [comment]
Fix was snuck in with PR #132
