### ISSUE TITLE
add phone number field

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#117]
## User Story
**As an** _output checker_,<br>
**I want** _to be able to phone the submitter of a request_<br>
**so that** _I can resolve issues that may not be easily solvable via the discussion tool_.

### ENV
- [x] `DEV`
- [x] `TEST`

### Acceptance criteria
Given a submitted request
When an output checker views the request
Then the output checker should see who submitted the request and their phone number

**Comment by Jonesy** [comment]
Fix was snuck in with PR #132
