### ISSUE TITLE
Logout should log you out

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#128]
**As a** _user of OCWA_,<br>
**I want** _to be able to logout_<br>
**so that** _others can't access my account_.

### ENV

- [ ] `DEV`
- [X] `TEST`
- [X] `PROD`

### TESTCASE

Log in as hodor
Logout
Click the Login button

### EXPECTED
I should be prompted for my username and password

### ACTUAL
I'm back in the app logged in as hodor

**Comment by Jonesy** [comment]
@BrandonSharratt I added a new `logoutURL` config value, should I wait until you've added that value to the build pipeline before submitting a PR or is it okay to do that first? The URL should be whatever the logout URL is in the known configuration, with `?redirect_uri=https://...` in the auth section of the config. Let me know also if I missed a helm value.
