### ISSUE TITLE
Files from previous request are being automatically added to new request

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#129]
### ENV
- [ ] `DEV`
- [X] `TEST`
- [ ] `PROD`

### TESTCASE
1.  Create a new request and upload a file
2.  Submit the request
3.  Return to the main page (list of requests)
4.  Create a new request
5.  Add a different file than the 1st request
6.  Submit the request

### EXPECTED
Only the 2nd file should be displayed on the request

### ACTUAL
The 2nd file is display but so is the 1st file (file from the previous request)

**Comment by pripley123** [comment]
[filefrompreviousrequestonnewrequest.json.txt](https://github.com/bcgov/OCWA/files/3087055/filefrompreviousrequestonnewrequest.json.txt)

**Comment by Jonesy** [comment]
Fix was snuck in with PR #132
