### ISSUE TITLE
Hide un-implemented feature from the action menus

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#130]
# OCWA Issue

## User Story

**As a** _requester/output checker,_<br>
**I want** _to only see actions I can do that are functional_<br>
**so that** _I can focus on actions I can do_.

### ENV

- [X] `DEV`
- [X] `TEST`

### TESTCASE
Duplicate functionality: Create, submit and cancel a request.  Then click "Duplicate".  

### EXPECTED
Duplicate functionality: The request would be duplicated OR we hide this action for now (recommended)

### ACTUAL
Duplicate functionality: Nothing happens

**Comment by Jonesy** [comment]
@pripley123 I couldn't reproduce the deny issue, can you confirm or get me a state file? Duplication works again.

**Comment by pripley123** [comment]
@Jonesy re: Deny issue.  I logged into test environment as hodor and viewed a request I had already claimed.  There is a "Deny" link in the Actions menu.  When I click it I get a message saying I'm not allowed to Deny requests.... I can get state file if you still need it

**Comment by Jonesy** [comment]
Yeah that'd be great, if you can export it after you get the error alert.

**Comment by pripley123** [comment]
State file attached
[state (3).json.txt](https://github.com/bcgov/OCWA/files/3133078/state.3.json.txt)

**Comment by Jonesy** [comment]
Discovered that the deny error is project based and will be moved into a new ticket as an enhancement versus a bug.
