### ISSUE TITLE
Access to User Instructional Guides and Support

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#139]
**As a** _researcher_,<br>
**I want** _to be confident that I can use the new features of the application_<br>
**so that** _I can perform my work with little need for external intervention_.

## Acceptance Criteria

Access to user documentation was one area that was discussed. 
Access to human support was another.

## Further Discussion
- What is this content/user instruction (video, text, links to webinar)?
- How will this content be updated (who are the content owners)?
- How often it will be updated (how robust does the solution have to be)?
- What are best practices around familiarizing new user's with a new tool (Just in time learning/Tool Tips?) 
- For access to human support, who are the support channels and what is the best way to contact them?

**Comment by pripley123** [comment]
So, if I could summarize where we landed in our meeting last week:

- technical issue guidance within OCWA --> configurable text; 
-- perhaps a "Help" menu item into the top nav dropdown which would open a window similar to the "About this App" window
- statistical requirements guidance within OCWA --> configurable link;  
-- not sure we nailed down location of where to display this link.  I'll create another comment with suggested location

**Comment by pripley123** [comment]
RE: where to display statistical requirements guidance within OCWA link
How hard would it be to embed in helper text? 
I'm looking at "Confidentiality disclosure to describe how it's upheld when criteria isn't met --> If you are submitting outputs which do not meet the rules of thumb, provide an explanation why the output entails no disclosure"  ... we could have an additional sentence of "For guidance, please review the <link title which would be the configurable link>

**Comment by pripley123** [comment]
Link to user guide (for the statistical requirements guidance): https://training.popdata.bc.ca/pluginfile.php/3450/mod_resource/content/1/Output%20Guide%20for%20Users.pdf
(Note you need to be in PopData's environment to access)
