### ISSUE TITLE
Export code (integration with GitLab) 

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#142]
**As a** _researcher/analyst_,<br>
**I want** _to be able to export code_<br>
**so that** _I can use code I created in the secure environment outside of the environment_.

### Acceptance criteria
**When** the researcher/analyst starts a new request i.e., clicks the "New Request" button
**Then** a choice of whether the output is code or data is presented

**Given** a researcher/analyst has started a new request
**When** they select the "data output" option
**Then** the existing workflow will be followed i.e., display the existing text fields e.g., variable description etc.

**Given** a researcher/analyst has started a new request
**When** they select the "code output" option 
**Then** a comments box for general comments about the code will be displayed in addition to the following existing fields: request title, phone number, Affirmation of Confidentiality
And the following code repo fields will be displayed: repo and branch in the research environment to export, external repository to send approved results

**Given** the fields of a code export request have been filled out
**When** the fields are submitted
**Then** the request summary page is displayed without the ability to upload files 

**When** the request is submitted and the automated scan passes
**Then** a merge request is automatically created in the "checkpoint" gitlab (which could be reviewed by an output checker)

**Comment by ikethecoder** [comment]
When an OCWA request is submitted, there will need to be a call out to create the Merge Request (will need: branch, external repo URL and internal repo name).  When the MR is approved, the work to export the files out to the external repo will be triggered from within Gitlab using a webhook.  So the only other touchpoint will be the approval of the MR.

An open design point regarding approval:
Option 1 - Approval is done in Gitlab using the MR and that automatically approves the OCWA request
Option 2 - Approval is done in OCWA and that triggers the approval of the MR in Gitlab

Thoughts?

**Comment by Jonesy** [comment]
I am guessing that would mean approval via the OC interface? Would we need extra layout details like code snippets or anything if so to show to the approver? The only hesitation I would have from going down option 2 is if we end up having to recreate a lot of the UI elements that are already present in GitLab. But if it's mostly just summary elements that I would be okay going down that path if it makes the request flow more contained to OCWA (which might be easier?)

**Comment by ikethecoder** [comment]
Effectively if we went with option 2, we would need to recreate the below.. which, unless there is a widget that does it, I think is probably not worth the effort.

OCWA could have a link to Gitlab - they click 'Merge' and then in OCWA the request is automatically approved.. OR, we disable the ability to Merge in Gitlab and require the OC to review in Gitlab and then approve in OCWA.

![Screen Shot 2019-06-25 at 11.47.48 AM.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/7ee243b9-55da-44d9-bd0b-1a1cb9df5b9d)

**Comment by pripley123** [comment]
I like the idea of being able to view in Gitlab (rather than re-create the interface in OCWA).

RE: where to do approval
My first intuition would be that approval be done in OCWA since that's the central place for an output checker approving things.  We'd also have the ability to control the interface in OCWA - we can use words like "Approve" which are unambiguous for approving a request as opposed to "Merge" in GitLab which is less so. However, I'm open to others thoughts on this...

**Comment by ikethecoder** [comment]
I like that Paul.. and we could present a link to the merge request in OCWA for the output checker, so that they don't have to look around for it in Gitlab.
