### ISSUE TITLE
Administrative reporting

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#143]
**As an** _administrator_,<br>
**I want** _to see reports and statistics on requests_<br>
**so that** _I can understand how people are using OCWA, and what things may be causing confusion or be pain points in the output checking process_.

## Acceptance criteria
To be determined.   This is a placeholder ticket which will either be updated with more detailed requirements or deleted in favour of smaller scoped tickets.

**Comment by pripley123** [comment]
Refined (and validated) requirements:

Requests that have been submitted (select-able date range)


Requester | Request name | Submitted date | Claimed date | First adjudication date* | Current request status | Checker name | File names(includes file type) | File sizes | Filewarnings
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |  

 	 	 	 	 	 	 	 	 	 
*date an output checker either approved or requested revisions for a request.  The first adjudication date would be used if multiple adjudication decisions were rendered e.g., a requester could submit and have an output checker request revisions multiple times before approving

**Comment by pripley123** [comment]
Meeting notes from today:

- each row is a submitted date - so one request that was submitted 3 times would have 3 rows.  This is because the list of files could be different between submissions.
- We decided we'd make columns sortable
- We'll require oc privilege as well as an admin reporting privilege to view reports
- On the api side of things we'll just need to make it able to handle a date range 
- most of the work is on the frontend
- we agreed to pivot if need be

**Comment by pripley123** [comment]
Additional requirements for Project level viewing/reporting:

Filter by project- or dashboard that shows summary stats for by project
Project Name
First Output submitted (regardless of requestor, this is a project stat)- click on it for more detail (who, what when etc..)
Last Output submitted /approved (same as above requirements)
Total # of outputs (approved/denied)
For Individual Level Viewing Dashboard:

Add Project Name for filtering
Add requestor name
Pull forward three fields from Output Form: Brief Description of Output, Relationship to future/previous Outputs and Files used in output.

**Comment by Jonesy** [comment]
Current layouts for reports (Dashboard, Code and Data Requests)
![Dashboard](https://user-images.githubusercontent.com/8776/61499644-d7055300-a97c-11e9-89de-80bcbf958b6c.png)
![Code Request](https://user-images.githubusercontent.com/8776/61499643-d7055300-a97c-11e9-815a-87e5951c4400.png)
![Data Request](https://user-images.githubusercontent.com/8776/61499645-d7055300-a97c-11e9-99fc-5ad2493f359b.png)
