### ISSUE TITLE
Tus d error when uploading valid file

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#144]
### ENV

- [x] `DEV`
- [x] `TEST`
- [ ] `PROD`

### TESTCASE
1.  Create a new request and fill out the mandatory fields
2. Upload a text file (I used one of the "valid" test files)

### EXPECTED

Text file would upload without error

### ACTUAL

Get a Tus d error message (screenshot attached)
- 

### ERROR

"tus: failed to create upload, caused by [object ProgressEvent], originated from request (response code: 0, response text: )

**Comment by pripley123** [comment]
![Capture](https://user-images.githubusercontent.com/33532439/57407536-41895e00-7198-11e9-8d95-af392343a58e.JPG)

**Comment by BrandonSharratt** [comment]
This was caused by a server migration
