### ISSUE TITLE
Default sort: last updated …. Most recent at the top

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#152]
**As a** _requester_,<br>
**I want** _to have the most recently updated requests showing at the top of my list of requests (i.e., default sort is last updated)_<br>
**so that** _I can quickly see which requests have the most recent activity_.

### ENV

- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### ACCEPTANCE CRITERIA
When requester view there list of requests
Then the sort order is by last modified date (most recent at the top)

**Comment by Jonesy** [comment]
Fixed in #142
