### ISSUE TITLE
Automated File Checker minimize false positives

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#154]
## User Story
**As a** _researcher_,<br>
**I want** _to import/export code that may contain a string pattern similar to a study id_<br>
**so that** _I can minimize false positive incidents, minimize the manual intervention that follows and improve workflow efficiency_. 

## Acceptance Criteria 
- example script should pass https://raw.githubusercontent.com/keras-team/keras/master/examples/addition_rnn.py

**Comment by pripley123** [comment]
Awaiting business rule confirmation re: study ids

**Comment by bdolor** [comment]
business rule change confirmed.
