### ISSUE TITLE
Add a file to my request after initially adding a file

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#155]
## User Story
**As a** _researcher_,<br>
**I want** _to be able to add a file to my request after initially adding a file_<br>
**so that** _I can fix mistakes or make additions I may have forgotten_.

### ENV

- [X] `DEV`
- [X] `TEST`
- [X] `PROD`

### Acceptance criteria
Given a researcher with access to OCWA
When the researcher
1. Creates a new request
2. Adds a valid output file
3. Click "Done editing"
4. Click "Edit request"
Then there should be an option to upload another file

Actual
The file upload spinner shows and it is not possible to add another file.  (You can add a file if you delete the existing file or if you refresh the page and edit, but researchers shouldn't have to do that)

**Comment by Jonesy** [comment]
Fixed in #142
