### ISSUE TITLE
Update the "Variable Descriptions" guidance text

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#156]
**As a** _operational maintainer of OCWA_,<br>
**I want** _to make the Variable Descriptions field guidance text clearer_<br>
**so that** _I can better communicate to requester what information is desired to be entered in this field_.

### ENV
- [X] `DEV`
- [X] `TEST`
- [X] `PROD`

### TESTCASE
When requester goes to the "New Request" page
Then the "Variable Descriptions" guidance text should say:

"Provide the variable/field names of the original and self-constructed variables. For original variables please use the name from the metadata."

**Comment by Jonesy** [comment]
Fixed in #142
