### ISSUE TITLE
Fields for a data import requests need revision

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#165]
**As a** _researcher_,<br>
**I want** _to be able to only provide relevant info about my non-row level data import_<br>
**so that** _I don't have to add information that is never used or irrelevant_.

### ENV

- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### EXPECTED

Fields should be:
General comments about the import
helper text: Describe any details about the import you wish

### ACTUAL

Most data import fields are currently irrelevant for imports

**Comment by Jonesy** [comment]
Fixed in `hotfix/form-and-text-fixes` branch.
