### ISSUE TITLE
Change "Data Import" new request drop down value to be "Other Import (e.g., documentation, code lists)​"

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#169]
## User Story
**As a** _research environment operator_,<br>
**I want** _to make it clear that we do no allow any data to be imported (should go through ingestion process instead)_<br>
**so that** _researchers are less likely to accidentally import things they should not_.

### ENV
- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE

Start a new import request

### EXPECTED

When you select your import type you have a choice of:
1) Code Import
2) Other Import (e.g., documentation, code lists)​

### ACTUAL

The dropdown has
Code import
Data import

**Comment by Jonesy** [comment]
Fixed in `hotfix/form-and-text-fixes` branch.
