### ISSUE TITLE
Code import text changes

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#170]
Misc text changes for import functionality

### ENV

- [X] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

"External repository to send approved results*"  … the external repo is where we're getting the code to import … so it's not approved.   Is this supposed to be the "Internal repository to send approved results"? or is it the "External repository to retrieve code from"?

 "Select Data Import Type" ... Should be "Select Import Type"

**Comment by Jonesy** [comment]
Fixed in `hotfix/form-and-text-fixes` branch.
