### ISSUE TITLE
Rename new request "Data Export" dropdown option to be "Aggregated data export (including notes/documentation)​"

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#171]
## User Story
**As a** _program manager_,<br>
**I want** _to make it clear that OCWA only supported exported aggregated results and not raw data_<br>
**so that** _there's less confusion for researchers as to what is appropriate to export_.

### ENV
- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE

From the main OCWA page
1. Click "New Request"

### EXPECTED
Dropdown options should be:
Aggregated data export (including notes/documentation)
Code export

### ACTUAL
Dropdown options currently are:
Data export
Code export

**Comment by Jonesy** [comment]
Fixed in `hotfix/form-and-text-fixes` branch.
