### ISSUE TITLE
Changes to Affirmation of Confidentiality statement text

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#175]
### ENV
- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE
Steps:
1. Create a new request

### EXPECTED
The Affirmation of Confidentiality statement for **exports** should be revised to be:
"By completing this form and submitting the output package for review, I affirm that the requested outputs have been aggregated such that they are anonymous and do not relate, or cannot be related, to an identifiable individual, business or organization and therefore are safe for release."

The Affirmation of Confidentiality statement for **imports** should be revised to be:
"By completing this form and submitting this information for import, I affirm that the import does not contain any data which could be used to identify an individual person or other Protected Data. I also affirm that there are no legal, contractual or policy restrictions which would limit the use of the information for the Approved Project."

### ACTUAL

Both export and import request forms use the same text:
"By completing this form and submitting the output package for review, I affirm that the requested outputs are safe for release and protect the confidentiality of data, to the best of my knowledge."

**Comment by Jonesy** [comment]
Fixed in `hotfix/form-and-text-fixes` branch.
