### ISSUE TITLE
Notification email text / url changes

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#183]
[OCWA - Request Update.pdf](https://github.com/bcgov/OCWA/files/3424102/OCWA.-.Request.Update.pdf)
I tried creating a data export request and approving it in Popdata Staging.  Here's the email I received.

The request id link appears to be missing a "/" in it.  Also, the "Log in to OCWA" link also appears to be broken.  

At least for exports, given you'd need to view in the SRE, there's not much value in hyperlinks.  

From: no-reply@popdata.bc.ca <no-reply@popdata.bc.ca>
Sent: 23 July 2019 14:02
To: Ripley, Paul CITZ:EX
Subject: OCWA - Request Update
 
Hi Paul Ripley,

A request that you are involved in #5d377544cc5e6e0012589b18 has been updated by John Outputchecker. Log in to OCWA to see more

### ENV

- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE
1. Create and submit a new request
2. Approve request

### EXPECTED
Requester should receive an email with either links that work or no links

### ACTUAL
The requester receives and email but the links are broken

**Comment by BrandonSharratt** [comment]
The ocwaURL config value for the request api is ONLY used in emails, and it has to have a trailing / in it if it does the email will form the url correctly. Additionally the templates are ALSO configurable so the email can be changed entirely without need for us to change any code

**Comment by pripley123** [comment]
@ikethecoder given the issues described in this ticket can be fixed via changes to config values, we'll need to factor these into our PopData config
