### ISSUE TITLE
Improve UX for URL fields on code export/import

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#208]
**As a** _researcher_,<br>
**I want** _to avoid encountering an error when I enter a git URL without .git appended to the URL string in the input field _<br>
**so that** _I can expedite my output or input request_.

# Conditions of Satisfaction
- A user enters a URL _without_ `.git` appended, form submission is successful
- A user enters a URL _with_ `.git` appended, form submission is successful

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [x] `Staging`

### TESTCASE

1. Log in to OCWA as requester.
2. Initiate a new Request.
3. Go to 'Initiate a New Code Export Request' page
4. Fill out all fields including either `Internal repository of code to export` text field with a valid Gitlab URL or `External repository to send approved results` with a valid Github URL but **without** `.git` appended to the end

### EXPECTED

Git URL's should be valid without requiring `.git`

### ACTUAL

They are not. Users familiar with git command line interface are used to `git clone <URL>` and are not required to append `.git`. The error message that follows is not as informative as it could be. 

### ERROR

![image.png](https://images.zenhubusercontent.com/5b27e04d4b5806bc2bd7ff05/efbe8e37-05db-4891-b6cc-08b40f2e3306)

## Notes

Likely this is the same for code imports

**Comment by ikethecoder** [comment]
#221
