### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#209]
## User Story
**As a** _developer_,<br>
**I want** _to work with the latest versions of dependencies_<br>
**so that** _I can keep third party libraries current, participate in dependency management best practices and have better assurance of future vulnerability protection_.

# Conditions of Satisfaction
- migrate terraform 11 to terraform 12 
- `npm outdated` produces the same values for 'current' and 'wanted' for forumApi, frontend, requestApi
- `pip list --outdated` produces the same values for 'version' and 'latest' for policyApi, validateApi

### Screenshots

![image.png](https://images.zenhubusercontent.com/5b27e04d4b5806bc2bd7ff05/f5737235-029a-4dcc-8a6f-362d385753be)

![image.png](https://images.zenhubusercontent.com/5b27e04d4b5806bc2bd7ff05/1470a1fa-055c-43e8-99c1-fbf60f543612)

**Comment by BrandonSharratt** [comment]
Updated the APIs. in feature/updateDependencies branch
