### ISSUE TITLE
Import size limits conflict with the max size for file validation

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#223]
**As a** _researcher_,<br>
**I want** _to be able to import file up to 20Mb_<br>
**so that** _I can efficiently bring in documentation into the research environment that will assist my research_.

### ENV
- [X] `DEV`
- [X] `TEST` 
- [ ] `PROD`  

### TESTCASE
1. Create a new non-code import request. 
2. Upload a file of 19.5MB
3. Upload a file of 20.1MB
4. Click "Done Editing"
5. Refresh the page (may need to give a bit of time for validation)

### EXPECTED
Based on https://proj.data.gov.bc.ca/jira/browse/PROOF-1769 validation for import files...
19.MB file should have a warning icon next to it
20.1MB file should have an error icon next to it with a file size error message

### ACTUAL
![image.png](https://images.zenhubusercontent.com/5a29c0b48a75884b908a5129/063e7206-b5e4-4369-badd-7401bd03b2b7)
All files display multiple "File is too large to validate" errors.  See attached screenshot.

**Comment by ikethecoder** [comment]
There are two bits of work here:
1) Rules currently do not distinguish between import vs export

2) The current "WORKING_LIMIT=5242880".  This would need to be adjusted to cover the absolute max - which is 20Mb or 20971520 bytes.
