### ISSUE TITLE
Repeating field in email notification template

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#238]
## User Story
**As an** _output checker_,<br>
**I want** _the email template to be free from duplicate content_<br>
**so that** _I can act on accurate information_.

# Conditions of Satisfaction
- The name of the requester `updater` / `triggeringUser['name']` in the email template does not repeat the last name

## template in question
- https://github.com/bcgov/OCWA/blob/master/microservices/requestApi/notifications/email/emailSubmitTemplate.html
## value to look at: 
- https://github.com/bcgov/OCWA/blob/master/microservices/requestApi/notifications/email/index.js#L43

**Comment by ikethecoder** [comment]
This is actually not a OCWA issue, but rather a misconfiguration the keycloak realm mappers that map data from AD/LDAP to the First Name.  Suggest to close based on the fact it is a deployment issue.
