### ISSUE TITLE
Non-code import requests in reports feature show fields that are not available to imports

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#246]
**As a** _operational manager_,<br>
**I want** _to see relevant field information regarding imports in the reports_<br>
**so that** _I can better understand the context of an import request_.

### ENV

- [x] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE
1. Create and submit a new non-code import request
2. Open the reports interface and view the request

### EXPECTED
The "General comments about the import" field would be displayed

### ACTUAL
The "Relationship to previous outputs" and the "Variable description" fields are displayed

![image.png](https://images.zenhubusercontent.com/5a29c0b48a75884b908a5129/61c35cdf-a4b1-4afe-b869-305e1697e010)

**Comment by Jonesy** [comment]
Import data requests now just have a `#request-details-purpose-text` element in the description section.
