### ISSUE TITLE
Reporting feature, errors 

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#255]
### ERROR 

loading the reporting page consistently produces errors with messages stating 'file not found' popping up in the bottom left on page load. The error was observed at the `ocwadl` subdomain with someone who was assigned the reporter role. The error was observed repeatedly and resolved itself, though inconsistently, with one or more page refreshes.

## Notes

I have asked for a screen shot of the errors from the user affected.

**Comment by bdolor** [comment]
screen shot of errors: 

![OCWA error copy](https://user-images.githubusercontent.com/2048170/69451855-3bfafc00-0d15-11ea-8d09-e423ddcd4120.png)

**Comment by pripley123** [comment]
This has been resolved.
