### ISSUE TITLE
Output checker approve button 

### ISSUE THREAD

**Issue by bdolor** [bcgov/OCWA#258]
## User Story
**As an** _output checker_,<br>
**I want** _to avoid hitting the approve button inadvertently/accidentally_<br>
**so that** _I minimize the chances of making a mistake, reducing the chances that I trigger automated processes_.

# Conditions of Satisfaction
- open for discussion...
- is the `assign to me` button and the `approve` button in the same place (risk of a double click)?
- introduce an intermediary step... `are you sure`, etc.

**Comment by Jonesy** [comment]
I have added a confirmation dialog before letting the approval go through, though I think this behaviour likely will break the integration tests. @pripley123 you might need to handle the confirmation dialog in Katalon, do you know if that's possible? If not I can probably switch to a more HTML/Atlaskit based approach of buttons with ID's that can be targeted easier.
