### ISSUE TITLE
Request Api - Email Notifications

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/OCWA#28]
## User Story
**As a** _user_,<br>
**I want** _to be emailed when a request is updated_<br>
**so that** _I know I have to log into OCWA_.

---
## Test Case

# ENV
`DEV`, `TEST`

# TESTCASE
Submit a request, then have an output checker pick it up

# EXPECTED
I should receive an email

# ACTUAL
No email is sent

**Comment by pripley123** [comment]
Successfully tested in test environment
