### ISSUE TITLE
Log in landing page

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/OCWA#29]
## User Story
**As a** _user_,<br>
**I want** _to be redirected after logging in to where I was before_<br>
**so that** _I don't have to find that page again_.

## Test Case

# TESTCASE
Open a request in a regular browser, then copy and paste that url in an incognito window and login

# EXPECTED
I land on the request page that I requested

# ACTUAL
I land on the request list page

**Comment by pripley123** [comment]
Tested in test environment.  I copied the url of a request.  When I opened an incognito window and pasted the request url, logged in, it sent me to the main dashboard page rather than the request page.

**Comment by Jonesy** [comment]
@pripley123 can you confirm this works for you? I think both Brandon and I were able to confirm this works for us.

**Comment by pripley123** [comment]
Successfully tested in test environment.
