### ISSUE TITLE
direct people that do not have a security group permitting them access to OCWA to a "Not authorized" page

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#31]
## User Story
**As an OCWA administrator,<br>
**I want to direct people that do not have a security group permitting them access to OCWA to a "Not authorized" page_<br>
**so that I can provide messages to users that describe what is preventing them from accessing OCWA
---
## Test Case

# ENV
TEST, DEV

# TESTCASE
Login to OCWA with an account that is in KeyCloak but does not have an OCWA security group set.

# EXPECTED
The user would be directed to a "Not authorized" page

# ACTUAL
The user can see the request list page but cannot do things that involve the APIs.

**Comment by gjlawran** [comment]
Confirmed.

**Comment by pripley123** [comment]
This works in test.
