### ISSUE TITLE
See warnings on files but not errors for uploaded files that should only trigger warnings

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#40]
## User Story
**As a requester_,<br>
**I want to see if my uploaded file generated a warning or was blocked_<br>
**so that** I can know if my files are acceptable to be exported.

## Test Case

# ENV
Test

# TESTCASE
Given:  I upload a file that should generate a file size warning (the threshold is configurable).
AND the file is a file I have never uploaded before (due to TusD remembering files it's seen before)
When: I view my uploaded file and the associated warning/errors associated with it

# EXPECTED
Then: I should see that my file has warning associated with it but not errors

# ACTUAL
My file had both "blocked" and "warning" icons
![capture](https://user-images.githubusercontent.com/33532439/52095747-0d8b1500-2579-11e9-8324-ab4779d41f97.JPG)

**Comment by BrandonSharratt** [comment]
In this particular case if a file is over 5mb it is ALSO over 3.5mb so you have triggered both the error and the warning, with the Error in this case being more pertinent. If we were going to remove one of them in this case I would suggest the error, HOWEVER we have no way of knowing that those 2 rules are similar.

**Comment by pripley123** [comment]
Sure, I can understand that the rules are independent from each other.  That's fine.  What this ticket is about is a file that should not trigger the error because the file size is lower than the 5Mb threshold

**Comment by pripley123** [comment]
Apologies @BrandonSharratt note sure where we landed with this one... perhaps we can chat tmo

**Comment by pripley123** [comment]
Given our testing this morning it seems like there's still an issue we need to sort out around this.   As I understand the issue seems to have to do with uploaded files being in a "Pending" state (so it seems like it's a larger issue than just warning errors).  If we have another ticket for that issue we could reference it here as a blocker for this one.

**Comment by pripley123** [comment]
Tested today in test environment - test passes so resolving this issue.
