### ISSUE TITLE
Deleting a file from the request does not work correctly

### ISSUE THREAD

**Issue by jujaga** [bcgov/OCWA#47]
## User Story

**As a** _exporter_,<br>
**I want** _to delete files from the request_<br>
**so that** _they are not a part of the request_.

## Test Case

# ENV

`DEV`

# TESTCASE

* Click New Request
* Click Add Files
* Upload a file (File A)
* Click Save & Close
* Navigate to the new request
* Click Edit Request
* Click Add Files
* Remove File A by clicking the x button
* Upload a different file (File B)

# EXPECTED

* Only File B should show up on the file list.

# ACTUAL

* Both File A and File B show up on the file list.

**Comment by pripley123** [comment]
Successfully tested in test environment.  Resolving.
