### ISSUE TITLE
Policy - Rules containing curly brace regex expressions do not work

### ISSUE THREAD

**Issue by jujaga** [bcgov/OCWA#51]
## User Story
**As a** _administrator of a secure analytics environment_,<br>
**I want** _the ability to automatically scan uploaded output file for Study IDs_<br>
**so that** _I can improve my confidence that row level data is not leaving the environment_.

## Test Case

# ENV
`DEV`, `TEST`

# TESTCASE
* The following Python rule should be executable:
`print(not bool(re.search(r'[\\w]{1}[\\d]{9}', ${file.content}.decode('utf-8'))))`

# EXPECTED
* The above rule executes and properly yields a pass or a fail

# ACTUAL
* The above rule fails for all files

**Comment by pripley123** [comment]
@jujaga I don't know how to verify in the test environment. Failing some guidance into how I can test this, I will leave this to others to verify it's working in the test environment.

**Comment by jujaga** [comment]
@pripley123 This should be verifiable as that the test environment contains the exact same test case rule as mentioned in this issue.

**Comment by pripley123** [comment]
Successfully tested in the test environment
