### ISSUE TITLE
Inform requester of errors in a way that allows requester to easily understand what they need to fix in their request

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#54]
## User Story
**As a** requester_,<br>
**I want**  to be informed of errors in a way that allows me to easily understand what I need to fix in my request<br>
**so that** I can be aware of and make needed changes.

## Test Case

# ENV
TEST

# TESTCASE
Generate an error e.g., duplicate request name
1. Create a new request
2. Fill out a name that is the same as a previous request
3. Save and close the request

# EXPECTED
An error message that describes what the issue is and what I need to do without technical details or jargon.  The error message would be displayed long enough for me to write down or take a screenshot of the error message.

# ACTUAL
A error message see screenshot is displayed temporarily on the screen
![ocwaduprequestname](https://user-images.githubusercontent.com/33532439/52678463-99406200-2ee6-11e9-9e38-7881a8fa8454.png)

**Comment by pripley123** [comment]
@BrandonSharratt @Jonesy My understanding was we were going to remove the duplicate error requirement... which would resolve the above issue with duplicate request title... if desired, I'm happy to close this ticket and put the duplicate title in a separate issue.

**Comment by BrandonSharratt** [comment]
The indexes that used to require it to be unique still existed in the requests table because of the old deploys. The index has been deleted and the environments should be fixed now (future environments were already fixed)

**Comment by pripley123** [comment]
Duplicate error still seems to occur in test environment.  (perhaps we haven't pushed latest master to it?)
