### ISSUE TITLE
Multiple file drag and drop yields inconsistent results

### ISSUE THREAD

**Issue by jujaga** [bcgov/OCWA#65]
# OCWA Issue

## User Story

**As a** _researcher_,<br>
**I want** _to be able to drag and drop multiple files at once into the file upload screen_<br>
**so that** _I can upload all the selected files at once_.

### ENV

- [x] `DEV`
- [x] `TEST`
- [ ] `PROD`

### TESTCASE

- Login and create new request
- Click Add files
- Drag and drop multiple files to the drag and drop element

### EXPECTED

- After some reasonable time, all of the files should be successfully submitted and be listed on the window.
- Furthermore, all files should also show in subsequent request pages.

### ACTUAL

- Only some of the files appear to be successfully submitted and listed on the window.
- Not all files show in subsequent request pages.
- During upload, there is a lot of element shuffling and other strange "jittery" behavior exhibited by the UI.

## Notes

- This is reproducible on both Windows and macOS on both Firefox and Chrome

**Comment by jujaga** [comment]
Verified on `DEV` - all files transferred and appear on request.

**Comment by pripley123** [comment]
Successfully tested in test environment
