### ISSUE TITLE
Refactor Request Sidebar Actions

### ISSUE THREAD

**Issue by Jonesy** [bcgov/OCWA#76]
# OCWA Issue

## User Story

**As a** _Exporter_,<br>
**I want** _to edit the state of a request easier_<br>
**so that** _I can work with the request_.

### ENV

`DEV`, `TEST`, `PROD`

### TESTCASE

- The sidebar actions on the request page each represent a specific API action that a user can make with a request. For example the **Withdraw Request** button only withdraws a request, but that can be confusing to users who don't know all the possible states a request can have and how they affect its placement in the review process.

### EXPECTED

- Revise the submitted request sidebar to show Edit (which will automatically withdraw) and Cancel
- Revise the Accepted/Cancelled/Refused request to only show a duplicate button which opens the dialog with the field pre-populated.

### ACTUAL

- Submitted request shows Withdraw and Cancel
- Accepted/Cancelled/Refused request shows no actions

**Comment by pripley123** [comment]
Successfully tested in test environment
