### ISSUE TITLE
Allow requesters to download in request app

### ISSUE THREAD

**Issue by Jonesy** [bcgov/OCWA#78]
# OCWA Issue

## User Story

**As a** _Requester_,<br>
**I want** _to be able to download file from the requests page_<br>
**so that** _I can look at files from other members of my team in the SRE_.

### ENV

`DEV`, `TEST`, `PROD`

### TESTCASE

- View any request with files saved to it

### EXPECTED

- Can download files from the request page

### ACTUAL

- Cannot download any files from the request page

**Comment by pripley123** [comment]
Successfully tested in test environment
