### ISSUE TITLE
As an output checker, I am not getting notified when there are new comments

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/OCWA#83]
# OCWA Issue

## User Story

**As a** _output checker_,<br>
**I want** _to be notified whenever a requester has added a comment to the discussion of a request that I am reviewing_<br>
**so that** _I can respond to the comment in a timely manner_.

### ENV

`STG`

### TESTCASE

- As a requestor, submit a request for review
- As an output checker, claim the same request
- As a requestor, write a comment in the request's discussion area

### EXPECTED

- Output checker is notified by email that a new comment has been added to the request discussion

### ACTUAL

- No email

**Comment by ikethecoder** [comment]
New PUT endpoints on the topic API are needed to subscribe/unsubscribe a user from a topic, by managing the contributors[] list on the topic.  The calls should be idempotent.

The Comment POST endpoint should then be updated to call the subscribe for the user that makes the comment.

**Comment by pripley123** [comment]
I'll leave this to others to validate in the test environment as I do not have access to email associated with any test oc accounts.

**Comment by pripley123** [comment]
here's what I received after a request I had claimed was re-submitted.  There's a url field that might need to be set.  I did not get any emails when new comments were made by the requester.

Hi Ho Dor,

A request that you are involved in #5c86f2bf9fb8d1001386488c has been updated by Paul Ripley. [{{url}}]Log in to OCWA to see more

**Comment by ikethecoder** [comment]
Verified in STG environment.
