### ISSUE TITLE
validation error false positive when submitting a request too quickly

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#89]
### ENV
`DEV`

### TESTCASE

Steps to replicate:
1. Create a new request
2. Upload the "test_valid_file_upload.txt" in the ui_tests/test_files folder
3. Once the submit button is enable, wait 3 seconds
4. Click the submit button

### EXPECTED
Successful submission

### ACTUAL
A validation error occurs.  If you wait a few seconds and try to submit again, submission works.

Redux state.json file uploaded.

**Comment by pripley123** [comment]
[validationerror_redux_state.json.txt](https://github.com/bcgov/OCWA/files/2916038/validationerror_redux_state.json.txt)

**Comment by pripley123** [comment]
![validationerror_ss](https://user-images.githubusercontent.com/33532439/53584428-64641a00-3b38-11e9-9a00-02a99c16dddc.JPG)

**Comment by Jonesy** [comment]
I am closing this due to the changes from #77
