### ISSUE TITLE
Output Checker Feedback and Adjustments

### ISSUE THREAD

**Issue by Jonesy** [bcgov/OCWA#90]
# OCWA Issue

## User Story

**As a** _Output Checker_,<br>
**I want** _some UI adjustments_<br>
**so that** _I can use the application more effectively_.

- [x] Sort the results by 
- [x] Add status Icon to the request page
- [x] Hide actions when the request has been sent back to the requester
- [x] Include a back link in the single request page
- [x] Start with OC's assigned requests only
- [x] Search filter in the left hand nav bar
- [x] Switch signed in menu option to `Signed In as [...]`
- [x] Scrolling doesn't work in Firefox
- [x] Unassigned is shown as assigned to the user when they shouldn't be

### ENV

`DEV`, `TEST`, `PROD`

### TESTCASE

- 

### EXPECTED

- 

### ACTUAL

-

**Comment by pripley123** [comment]
Successfully tested in test environment
