### ISSUE TITLE
Enhance file validation outcome text to make more readable

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#94]
## User Story
**As a** _requester_,<br>
**I want** _to see and easily understand what validation rules passed / files for each file I uploaded_<br>
**so that** _I can quickly see if and what changes I need to make to my uploaded files_.

Acceptance criteria:
Validation outcome messages display the new text (as specified below)

### ENV
- [x] `DEV`
- [x] `TEST`

Current text is in screen shot.
Updated text:
Not a warning file type
Not a blocked file type
File size is under 3.5Mb
File size is under 5Mb
No study ids are present in the content

![test multi tomato.JPG](https://images.zenhubusercontent.com/5a29c0b48a75884b908a5129/bc841a0e-38d8-45e5-8544-7671a3566e3f)

**Comment by Jonesy** [comment]
@pripley123 @BrandonSharratt I can reformat the string that gets sent in the response; replace the underscores with spaces and capitalize the first string pretty easily, but I would recommend changing it on the API side instead so the frontend can be a little more dumb and just show what it's sent. Thoughts?

**Comment by jujaga** [comment]
I suspect the best method would just be to have it be encoded differently in the database instead of reformatting on the API side.

**Comment by pripley123** [comment]
successfully tested in test environment
